window.MyApp = MyApp ? {}

window.MyApp.itBehavesLike = (name, args...) ->
  switch name
    when 'Selectable' then window.MyApp.sharedSpecs.controllers.selectable args...
    when 'Crudable' then window.MyApp.sharedSpecs.controllers.crudable args...
    when 'SimpleCrudable' then window.MyApp.sharedSpecs.services.simpleCrudable args...
    else throw "Unknown shared spec '#{name}'"
  